version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat_dev
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
